<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testtrack" nsURI="http://www.example.org/testtrack" nsPrefix="testtrack">
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracksegment" eType="#//TrackSegment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoadSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roadcomponents" upperBound="-1"
        eType="#//RoadComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signs" upperBound="-1"
        eType="#//Sign" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    <eLiterals name="NORTH"/>
    <eLiterals name="EAST" value="1"/>
    <eLiterals name="SOUTH" value="2"/>
    <eLiterals name="WEST" value="3"/>
    <eLiterals name="NORTHEAST" value="4"/>
    <eLiterals name="SOUTHEAST" value="5"/>
    <eLiterals name="SOUTHWEST" value="6"/>
    <eLiterals name="NORTHWEST" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActorType">
    <eLiterals name="CAR"/>
    <eLiterals name="BUS" value="1"/>
    <eLiterals name="BICYCLE" value="2"/>
    <eLiterals name="MOTORCYCLE" value="3"/>
    <eLiterals name="GOLFCART" value="4"/>
    <eLiterals name="PEDESTRIAN" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrackSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roadsegments" upperBound="-1"
        eType="#//RoadSegment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoadComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="#//RoadComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comesFrom" eType="#//Lane"
        eOpposite="#//Lane/leadsTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadsTo" eType="#//Lane"
        eOpposite="#//Lane/comesFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sidewalk" eSuperTypes="#//RoadComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPosition" eType="#//RoadComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endPosition" eType="#//RoadComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sign"/>
  <eClassifiers xsi:type="ecore:EClass" name="Crosswalk" eSuperTypes="#//Sign"/>
  <eClassifiers xsi:type="ecore:EClass" name="StopSign" eSuperTypes="#//Sign"/>
  <eClassifiers xsi:type="ecore:EClass" name="GiveWaySign" eSuperTypes="#//Sign"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeadEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="Roundabout"/>
</ecore:EPackage>
